### ISSUE TITLE
Is there a way to use Time::Moment from xs?

### ISSUE THREAD

**Issue by yuki-kimoto** [chansen/p5-time-moment#11]
Is there a way to use Time::Moment from xs?

**Comment by chansen** [comment]
As it stand today, I think this is out of the scope for the `Time::Moment` project as most of `Time::Moment`´s C code is tied to Perl/XS. Before I started to implement `Time::Moment` I wrote a C library named [c-dt](https://github.com/chansen/c-dt) which is a cornerstone in `Time::Moment`.  I'm sure you could use [c-dt](https://github.com/chansen/c-dt) and study `Time::Moment`'s [C code](https://github.com/chansen/p5-time-moment/blob/master/src/moment.c) and write something that's superior to R's performance and API (c-dt provides many things that's not exposed in Time::Moment)!  If you want any feedback or help, don't hesitate to send me an email.

**Comment by yuki-kimoto** [comment]
Oh, Pure C library. Greate! I try to use this C library to implement Rstats time culculation.

**Comment by chansen** [comment]
I'm [0xCH](https://twitter.com/0xCH) on Twitter, a blog at [blogs.perl.org](http://blogs.perl.org/users/chansen/) and I'm always connected on [irc.perl.org](irc://irc.perl.org) as chansen.

**Comment by yuki-kimoto** [comment]
thanks!
