### ISSUE TITLE
How to clone Time::Moment object?

### ISSUE THREAD

**Issue by Pilat66** [chansen/p5-time-moment#25]
How to clone Time::Moment object?
Analog  DateTime->clone().

**Comment by chansen** [comment]
Why would you want to clone an instance of `Time::Moment`? `Time::Moment` instances are immutable.

--
chansen

**Comment by Pilat66** [comment]
Thanks for the answer and sorry for the stupid question.
I read the documentation and understood that you are right. I was confused by the fact that I still worked mostly with DateTime.
