### ISSUE TITLE
delta_days() does not return complete days

### ISSUE THREAD

**Issue by 0x62ash** [chansen/p5-time-moment#30]
```perl -le 'use Time::Moment; print Time::Moment->from_string("2018-01-01T18:00:00Z")->delta_days(Time::Moment->from_string("2018-01-02T01:00:00Z"));'```

Expect: 0
Got: 1

PS.
As opposite delta_hours works ok:
```perl -le 'use Time::Moment; print Time::Moment->from_string("2018-01-01T18:30:00Z")->delta_hours(Time::Moment->from_string("2018-01-01T19:29:00Z"));'```
Expect: 0
Got: 0

**Comment by 0x62ash** [comment]
Thank you for response

> When daylight saving time begins or ends it’s not uncommon for transition days to be 23 or 25 hours long.

Could you explain it in details? For example what's wrong with this snippet:

```
sub complete_delta_days {
    my ($dt1, $dt2) = @_;
    my $delta = $dt1->delta_days($dt2);

    if ($delta > 0 && $dt1->strftime('%H:%M:%S') gt $dt2->strftime('%H:%M:%S')) {
        return $delta - 1;
    } elsif ( $delta < 0 && $dt1->strftime('%H:%M:%S') lt $dt2->strftime('%H:%M:%S') ) {
        return $delta + 1;
    } else {
        return $delta;
    }
}
```

**Comment by chansen** [comment]
I have no idea what you intend with you routine `complete_delta_days()`, but here is two fictive transistion from DST and to DST:

```perl
use Test::More;

# Fictive transition to DST (could be a European or US time zone)
{
    my $tm1 = Time::Moment->from_string('2018-03-24T03+01');
    my $tm2 = Time::Moment->from_string('2018-03-25T03+02');
    is($tm1->delta_hours($tm2), 23);
    is($tm1->delta_days($tm2), 1);
}

# Fictive transition from DST (could be a European or US time zone)
{
    my $tm1 = Time::Moment->from_string('2018-03-27T03+02');
    my $tm2 = Time::Moment->from_string('2018-03-28T03+01');
    is($tm1->delta_hours($tm2), 25);
    is($tm1->delta_days($tm2), 1);
}

done_testing;
```
Please note that one cannot rely on transition days to be 23 or 25 hours long, it's a political decision and has precedent cases.

**Comment by chansen** [comment]
Feel free to comment if you want clarification!

--
chansen

**Comment by 0x62ash** [comment]
Looks like we have different definition for "complete" days.
Ok, closing this bug.

**Comment by chansen** [comment]
I would really appreciate if you clarified your interpretation/definition of "complete" days.

--
chansen

**Comment by 0x62ash** [comment]
After googling I can't provide your any good definition. "complete" days is vague term

**Comment by chansen** [comment]
I thank you for your efforts! If you have any further questions/issues please open an issue!

--
chansen

**Comment by eserte** [comment]
I also stumbled over this issue. My naïve understanding of "complete days" is that the following yields the same

    $tm1->delta_days($tm2)

and

    int($tm1->delta_hours($tm2)/24)

at least in ranges where no DST switches are involved. If this cannot be changed, then maybe it can be documented?
