### ISSUE TITLE
Test units needs to be expanded to cover the API of Time::Moment

### ISSUE THREAD

**Issue by chansen** [chansen/p5-time-moment#33]
## Time::Moment:
Untested routines XXX

## Time::Moment::Adjusters:
- [x] #51
- [x] Time::Moment::Adjuster::LastDayOfWeekInMonth()
- [x] Time::Moment::Adjuster::NthDayOfWeekInMonth()
- [x] Time::Moment::Adjuster::WesternEasterSunday()
- [x] Time::Moment::Adjuster::OrthodoxEasterSunday()
- [x] Time::Moment::Adjuster::NearestMinuteInterval()

**Comment by sshine** [comment]
Still haven't tested `OrthodoxEasterSunday`. Tests for `WesternEasterSunday` should be sufficient.

Let me know what you think about the tests for `FirstDayOfWeekInMonth`, `LastDayOfWeekInMonth` and `NthDayOfWeekInMonth`. I tried to make them somewhat property-based. Also, feel free to re-format them. I have a feeling that you have a consistent style that I'd like to adapt from. :-)

Tests for `NearestMinuteInterval` are crude still. Haven't had time to think about some good, general properties.
