### ISSUE TITLE
Example format strings - digits in the year

### ISSUE THREAD

**Issue by richlv** [chansen/p5-time-moment#45]
In https://metacpan.org/pod/Time::Moment#EXAMPLE-FORMAT-STRINGS , there's a line:

    %y%m                        201212      (reduced accuracy)

https://metacpan.org/pod/Time::Moment#%y says:

    Replaced by the last two digits of the year as a decimal number [00, 99].

It looks like the example should either use ```%Y%m``` or ```1212```.

**Comment by chansen** [comment]
Yes you are correct, documentation should use `%Y` and not `%y`.

**Comment by richlv** [comment]
Yay, thank you :)
