### ISSUE TITLE
when parsing strings, "T" and "Z" should be case-insensitive

### ISSUE THREAD

**Issue by karenetheridge** [chansen/p5-time-moment#46]
https://tools.ietf.org/html/rfc3339#section-5.6 states:

> NOTE: Per [ABNF] and ISO8601, the "T" and "Z" characters in this syntax may alternatively be lower case "t" or "z" respectively.

However, the parser code does not accept "t" or "z".

**Comment by chansen** [comment]
The time designator `T` and the UTC designator `Z` is specified as upper case in ISO 8601:2004. If you want to accept lower case you would have to use the lenient option.
