### ISSUE TITLE
y2038 bug

### ISSUE THREAD

**Issue by bmwiedemann** [chansen/p5-time-moment#47]
As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +16 years, because that is how long I expect some software will be used in some places.
This showed up failing tests in our `perl-Time-Moment` package build.
See https://reproducible-builds.org/ for why this matters.

To reproduce:
```
sudo date --set 2038-01-20
perl -e 'use Time::Moment; print Time::Moment->now()'
Parameter 'offset' is out of the range [-1080, 1080] at -e line 1.
```

also, the Time::Moment tests fail probably for the same reason.

**Comment by chansen** [comment]
Thank you for the pull request!
