### ISSUE TITLE
Add days diff support

### ISSUE THREAD

**Issue by dshadow** [chansen/p5-time-moment#9]
Please check:
https://github.com/chansen/p5-time-moment/pull/8

**Comment by chansen** [comment]
I have released [Time::Moment](https://metacpan.org/pod/distribution/Time-Moment/lib/Time/Moment.pod) v31 to CPAN, which has a [delta_days](https://metacpan.org/pod/distribution/Time-Moment/lib/Time/Moment.pod#delta_days) method.

**Comment by dshadow** [comment]
Nice! Thank you!
